export const courseCategories = [
  "Programming & Development",
  "Data Science & AI",
  "Cyber Security",
  "Cloud Computing",
  "DevOps",
  "Web Development",
  "Mobile App Development",
  "UI/UX Design",
  "Graphic Design",
  "Digital Marketing",
  "Business & Management",
  "Finance & Accounting",
  "Stock Market & Trading",
  "Entrepreneurship",
  "Communication Skills",
  "English Speaking",
  "Personality Development",
  "Career Development",
  "Interview Preparation",
  "Resume Building",
  "Government Exam Preparation",
  "UPSC",
  "SSC",
  "Banking",
  "Railway Exams",
  "Defence Exams",
  "Teaching Exams",
  "State PSC",
  "NEET",
  "JEE",
  "GATE",
  "CAT",
  "CUET",
  "Class 6-10",
  "Class 11-12",
  "Commerce",
  "Science",
  "Arts & Humanities",
  "Computer Science",
  "Information Technology",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Law",
  "Medical",
  "Nursing",
  "Pharmacy",
  "Agriculture",
  "Architecture",
  "Animation & VFX",
  "Video Editing",
  "Photography",
  "Music",
  "Cooking",
  "Yoga & Fitness",
  "Health & Wellness",
  "Spoken Languages",
  "Foreign Languages",
  "Soft Skills",
  "Project Management",
  "Microsoft Office",
  "Excel",
  "Tally & GST",
  "Ethical Hacking",
  "Blockchain",
  "Machine Learning",
  "Artificial Intelligence",
  "Robotics",
  "IoT",
  "Kids Learning",
  "Competitive Coding",
  "Freelancing",
  "Content Writing",
  "Other"
] as const;